// ==============================================================================================
// FILE: ast/ast.go
// ==============================================================================================
// PACKAGE: ast (Abstract Syntax Tree)
// PURPOSE: Defines the hierarchical data structures that represent the source code.
//          The AST is generated by the Parser and consumed by the Evaluator.
//          It provides a structured, type-safe representation of the Eloquence language,
//          abstracting away the linear complexity of raw tokens.
// ==============================================================================================

package ast

import (
	"bytes"

	"eloquence/token"
)

// ----------------------------------------------------------------------------------------------
// INTERFACES
// ----------------------------------------------------------------------------------------------

// Node is the base interface for all elements in the Abstract Syntax Tree.
// Every piece of code, from a simple integer to a complex function definition, is a Node.
type Node interface {
	// TokenLiteral returns the literal string of the token associated with this node.
	// Used primarily for debugging and error reporting.
	TokenLiteral() string

	// String returns a string representation of the node.
	// This reconstructs the original source code (or close to it) from the tree.
	String() string
}

// Statement represents a node that performs an action but does not return a value.
// Examples: "x is 10" (Assignment), "return x", "define User as struct".
type Statement interface {
	Node
	statementNode() // Marker method to distinguish Statements from Expressions
}

// Expression represents a node that evaluates to a value.
// Examples: "5", "x adds y", "takes(x) { ... }".
type Expression interface {
	Node
	expressionNode() // Marker method to distinguish Expressions from Statements
}

// ----------------------------------------------------------------------------------------------
// ROOT NODE
// ----------------------------------------------------------------------------------------------

// Program is the root node of every AST.
// It represents the entire source file as a sequence of statements.
type Program struct {
	Statements []Statement // The linear list of top-level statements
}

func (p *Program) TokenLiteral() string {
	if len(p.Statements) > 0 {
		return p.Statements[0].TokenLiteral()
	}
	return ""
}

// String reconstructs the entire program source code.
func (p *Program) String() string {
	var out bytes.Buffer
	for _, s := range p.Statements {
		out.WriteString(s.String())
	}
	return out.String()
}

// ----------------------------------------------------------------------------------------------
// STATEMENTS
// ----------------------------------------------------------------------------------------------

// AssignmentStatement represents binding a value to a variable.
// Syntax: <IDENTIFIER> is <EXPRESSION>
// Example: x is 5
type AssignmentStatement struct {
	Token token.Token // The 'IDENT' token of the variable name (historical artifact of parsing)
	Name  *Identifier // The variable being assigned to
	Value Expression  // The value being assigned
}

func (as *AssignmentStatement) statementNode()       {}
func (as *AssignmentStatement) TokenLiteral() string { return as.Token.Literal }
func (as *AssignmentStatement) String() string {
	return as.Name.String() + " is " + as.Value.String()
}

// ReturnStatement represents exiting a function with a value.
// Syntax: return <EXPRESSION>
type ReturnStatement struct {
	Token       token.Token // The 'return' token
	ReturnValue Expression  // The value to return (can be nil)
}

func (rs *ReturnStatement) statementNode()       {}
func (rs *ReturnStatement) TokenLiteral() string { return rs.Token.Literal }
func (rs *ReturnStatement) String() string {
	var out bytes.Buffer
	out.WriteString("return ")
	if rs.ReturnValue != nil {
		out.WriteString(rs.ReturnValue.String())
	}
	return out.String()
}

// ShowStatement is a built-in statement for printing to stdout.
// Syntax: show <EXPRESSION>
type ShowStatement struct {
	Token token.Token // The 'show' token
	Value Expression  // The expression to print
}

func (ss *ShowStatement) statementNode()       {}
func (ss *ShowStatement) TokenLiteral() string { return ss.Token.Literal }
func (ss *ShowStatement) String() string {
	return "show " + ss.Value.String()
}

// ExpressionStatement allows an expression to stand alone as a statement.
// Example: "x adds 5" on a line by itself (valid, though result is discarded unless implicit return).
type ExpressionStatement struct {
	Token      token.Token // The first token of the expression
	Expression Expression
}

func (es *ExpressionStatement) statementNode()       {}
func (es *ExpressionStatement) TokenLiteral() string { return es.Token.Literal }
func (es *ExpressionStatement) String() string {
	if es.Expression != nil {
		return es.Expression.String()
	}
	return ""
}

// BlockStatement represents a grouped sequence of statements.
// Used in If/Else blocks, Loops, and Function bodies.
type BlockStatement struct {
	Token      token.Token // The opening delimiter (e.g., '{' or implicit start)
	Statements []Statement
}

func (bs *BlockStatement) statementNode()       {}
func (bs *BlockStatement) TokenLiteral() string { return bs.Token.Literal }
func (bs *BlockStatement) String() string {
	var out bytes.Buffer
	for _, s := range bs.Statements {
		out.WriteString(s.String())
	}
	return out.String()
}

// PointerAssignmentStatement represents writing to a memory address.
// Syntax: pointing from <IDENTIFIER> is <EXPRESSION>
type PointerAssignmentStatement struct {
	Token token.Token // The 'pointing from' token
	Name  *Identifier // The pointer variable
	Value Expression  // The new value
}

func (pas *PointerAssignmentStatement) statementNode()       {}
func (pas *PointerAssignmentStatement) TokenLiteral() string { return pas.Token.Literal }
func (pas *PointerAssignmentStatement) String() string {
	return "pointing from " + pas.Name.String() + " is " + pas.Value.String()
}

// StructDefinitionStatement defines a new custom data type.
// Syntax: define <NAME> as struct { <FIELDS> }
type StructDefinitionStatement struct {
	Token      token.Token   // The 'define' token
	Name       *Identifier   // The name of the struct (e.g., "User")
	Attributes []*Identifier // The list of field names
}

func (sds *StructDefinitionStatement) statementNode()       {}
func (sds *StructDefinitionStatement) TokenLiteral() string { return sds.Token.Literal }
func (sds *StructDefinitionStatement) String() string {
	var out bytes.Buffer
	out.WriteString("define " + sds.Name.String() + " as struct { ")
	for i, a := range sds.Attributes {
		out.WriteString(a.String())
		if i < len(sds.Attributes)-1 {
			out.WriteString(", ")
		}
	}
	out.WriteString(" }")
	return out.String()
}

// LoopStatement represents a conditional loop.
// Syntax: while <CONDITION> <BLOCK>
type LoopStatement struct {
	Token     token.Token // The 'while' or 'for' token
	Condition Expression  // The loop guard
	Body      *BlockStatement
}

func (ls *LoopStatement) statementNode()       {}
func (ls *LoopStatement) TokenLiteral() string { return ls.Token.Literal }
func (ls *LoopStatement) String() string {
	return ls.Token.Literal + " " + ls.Condition.String() + " " + ls.Body.String()
}

// TryCatchStatement represents error handling blocks.
// Syntax: try <BLOCK> catch <BLOCK> finally <BLOCK>
type TryCatchStatement struct {
	Token        token.Token // The 'try' token
	TryBlock     *BlockStatement
	CatchBlock   *BlockStatement
	FinallyBlock *BlockStatement
}

func (tc *TryCatchStatement) statementNode()       {}
func (tc *TryCatchStatement) TokenLiteral() string { return tc.Token.Literal }
func (tc *TryCatchStatement) String() string {
	var out bytes.Buffer
	out.WriteString("try " + tc.TryBlock.String())
	if tc.CatchBlock != nil {
		out.WriteString(" catch " + tc.CatchBlock.String())
	}
	if tc.FinallyBlock != nil {
		out.WriteString(" finally " + tc.FinallyBlock.String())
	}
	return out.String()
}

// ----------------------------------------------------------------------------------------------
// EXPRESSIONS
// ----------------------------------------------------------------------------------------------

// Identifier represents a variable usage.
// Example: x
type Identifier struct {
	Token token.Token // The 'IDENT' token
	Value string      // The name of the identifier
}

func (i *Identifier) expressionNode()      {}
func (i *Identifier) TokenLiteral() string { return i.Token.Literal }
func (i *Identifier) String() string       { return i.Value }

// IntegerLiteral represents a whole number.
// Example: 42
type IntegerLiteral struct {
	Token token.Token
	Value int64
}

func (il *IntegerLiteral) expressionNode()      {}
func (il *IntegerLiteral) TokenLiteral() string { return il.Token.Literal }
func (il *IntegerLiteral) String() string       { return il.Token.Literal }

// FloatLiteral represents a decimal number.
// Example: 3.14
type FloatLiteral struct {
	Token token.Token
	Value float64
}

func (fl *FloatLiteral) expressionNode()      {}
func (fl *FloatLiteral) TokenLiteral() string { return fl.Token.Literal }
func (fl *FloatLiteral) String() string       { return fl.Token.Literal }

// StringLiteral represents a text string.
// Example: "Hello"
type StringLiteral struct {
	Token token.Token
	Value string
}

func (sl *StringLiteral) expressionNode()      {}
func (sl *StringLiteral) TokenLiteral() string { return sl.Token.Literal }
func (sl *StringLiteral) String() string       { return `"` + sl.Value + `"` }

// CharLiteral represents a single character.
// Example: 'a'
type CharLiteral struct {
	Token token.Token
	Value rune
}

func (cl *CharLiteral) expressionNode()      {}
func (cl *CharLiteral) TokenLiteral() string { return cl.Token.Literal }
func (cl *CharLiteral) String() string       { return "'" + string(cl.Value) + "'" }

// BooleanLiteral represents true or false.
type BooleanLiteral struct {
	Token token.Token
	Value bool
}

func (bl *BooleanLiteral) expressionNode()      {}
func (bl *BooleanLiteral) TokenLiteral() string { return bl.Token.Literal }
func (bl *BooleanLiteral) String() string       { return bl.Token.Literal }

// NilLiteral represents 'none' (null/nil).
type NilLiteral struct {
	Token token.Token
}

func (nl *NilLiteral) expressionNode()      {}
func (nl *NilLiteral) TokenLiteral() string { return nl.Token.Literal }
func (nl *NilLiteral) String() string       { return "none" }

// PrefixExpression represents an operator before an operand.
// Example: -5, !true
type PrefixExpression struct {
	Token    token.Token // The prefix token (e.g., !, -)
	Operator string
	Right    Expression
}

func (pe *PrefixExpression) expressionNode()      {}
func (pe *PrefixExpression) TokenLiteral() string { return pe.Token.Literal }
func (pe *PrefixExpression) String() string {
	return "(" + pe.Operator + " " + pe.Right.String() + ")"
}

// InfixExpression represents a binary operation.
// Example: 5 adds 10, x equals y
type InfixExpression struct {
	Token    token.Token // The operator token
	Left     Expression
	Operator string
	Right    Expression
}

func (ie *InfixExpression) expressionNode()      {}
func (ie *InfixExpression) TokenLiteral() string { return ie.Token.Literal }
func (ie *InfixExpression) String() string {
	return "(" + ie.Left.String() + " " + ie.Operator + " " + ie.Right.String() + ")"
}

// PointerReferenceExpression gets the address of a variable.
// Syntax: pointing to <IDENTIFIER>
type PointerReferenceExpression struct {
	Token token.Token
	Value Expression
}

func (pr *PointerReferenceExpression) expressionNode()      {}
func (pr *PointerReferenceExpression) TokenLiteral() string { return pr.Token.Literal }
func (pr *PointerReferenceExpression) String() string {
	return "(pointing to " + pr.Value.String() + ")"
}

// PointerDereferenceExpression gets the value at an address.
// Syntax: pointing from <IDENTIFIER>
type PointerDereferenceExpression struct {
	Token token.Token
	Value Expression
}

func (pd *PointerDereferenceExpression) expressionNode()      {}
func (pd *PointerDereferenceExpression) TokenLiteral() string { return pd.Token.Literal }
func (pd *PointerDereferenceExpression) String() string {
	return "(pointing from " + pd.Value.String() + ")"
}

// IfExpression represents a conditional logic branch that returns a value.
// Syntax: if <COND> <BLOCK> else <BLOCK>
type IfExpression struct {
	Token       token.Token
	Condition   Expression
	Consequence *BlockStatement
	Alternative *BlockStatement
}

func (ie *IfExpression) expressionNode()      {}
func (ie *IfExpression) TokenLiteral() string { return ie.Token.Literal }
func (ie *IfExpression) String() string {
	var out bytes.Buffer
	out.WriteString("if " + ie.Condition.String() + " " + ie.Consequence.String())
	if ie.Alternative != nil {
		out.WriteString(" else " + ie.Alternative.String())
	}
	return out.String()
}

// FunctionLiteral represents an anonymous function definition.
// Syntax: takes (params) <BLOCK>
type FunctionLiteral struct {
	Token      token.Token // The 'takes' token
	Parameters []*Identifier
	Body       *BlockStatement
}

func (fl *FunctionLiteral) expressionNode()      {}
func (fl *FunctionLiteral) TokenLiteral() string { return fl.Token.Literal }
func (fl *FunctionLiteral) String() string {
	var out bytes.Buffer
	out.WriteString("takes (")
	for i, p := range fl.Parameters {
		out.WriteString(p.String())
		if i < len(fl.Parameters)-1 {
			out.WriteString(", ")
		}
	}
	out.WriteString(") " + fl.Body.String())
	return out.String()
}

// CallExpression represents executing a function.
// Syntax: myFunc(1, 2)
type CallExpression struct {
	Token     token.Token // The '(' token
	Function  Expression  // The identifier or function literal being called
	Arguments []Expression
}

func (ce *CallExpression) expressionNode()      {}
func (ce *CallExpression) TokenLiteral() string { return ce.Token.Literal }
func (ce *CallExpression) String() string {
	var out bytes.Buffer
	out.WriteString(ce.Function.String() + "(")
	for i, a := range ce.Arguments {
		out.WriteString(a.String())
		if i < len(ce.Arguments)-1 {
			out.WriteString(", ")
		}
	}
	out.WriteString(")")
	return out.String()
}

// ArrayLiteral represents a list of values.
// Syntax: [1, 2, 3]
type ArrayLiteral struct {
	Token    token.Token // The '[' token
	Elements []Expression
}

func (al *ArrayLiteral) expressionNode()      {}
func (al *ArrayLiteral) TokenLiteral() string { return al.Token.Literal }
func (al *ArrayLiteral) String() string {
	var out bytes.Buffer
	out.WriteString("[")
	for i, el := range al.Elements {
		out.WriteString(el.String())
		if i < len(al.Elements)-1 {
			out.WriteString(", ")
		}
	}
	out.WriteString("]")
	return out.String()
}

// IndexExpression represents accessing an array or map.
// Syntax: arr[1]
type IndexExpression struct {
	Token token.Token // The '[' token
	Left  Expression  // The object being indexed
	Index Expression  // The key or index
}

func (ie *IndexExpression) expressionNode()      {}
func (ie *IndexExpression) TokenLiteral() string { return ie.Token.Literal }
func (ie *IndexExpression) String() string {
	return "(" + ie.Left.String() + "[" + ie.Index.String() + "])"
}

// MapLiteral represents a hash map.
// Syntax: { key: value, ... }
type MapLiteral struct {
	Token token.Token // The '{' token
	Pairs map[Expression]Expression
}

func (ml *MapLiteral) expressionNode()      {}
func (ml *MapLiteral) TokenLiteral() string { return ml.Token.Literal }
func (ml *MapLiteral) String() string {
	return "{...}" // Simplified for string representation
}

// StructField helps construct struct instances.
type StructField struct {
	Name  *Identifier
	Value Expression
}

// StructInstantiationExpression creates an instance of a defined struct.
// Syntax: User { name: "Amogh", age: 30 }
type StructInstantiationExpression struct {
	Token  token.Token // The first token of the identifier
	Name   *Identifier // The name of the struct type
	Fields []StructField
}

func (sie *StructInstantiationExpression) expressionNode()      {}
func (sie *StructInstantiationExpression) TokenLiteral() string { return sie.Token.Literal }
func (sie *StructInstantiationExpression) String() string {
	var out bytes.Buffer
	out.WriteString(sie.Name.String() + " { ")
	for i, f := range sie.Fields {
		out.WriteString(f.Name.String() + ": " + f.Value.String())
		if i < len(sie.Fields)-1 {
			out.WriteString(", ")
		}
	}
	out.WriteString(" }")
	return out.String()
}

// FieldAccessExpression represents accessing a property of a struct.
// Syntax: user.name
type FieldAccessExpression struct {
	Token  token.Token // The '.' token
	Object Expression  // The struct instance
	Field  *Identifier // The property name
}

func (fae *FieldAccessExpression) expressionNode()      {}
func (fae *FieldAccessExpression) TokenLiteral() string { return fae.Token.Literal }
func (fae *FieldAccessExpression) String() string {
	return "(" + fae.Object.String() + "." + fae.Field.String() + ")"
}
