// ==============================================================================================
// FILE: ast/ast.go
// ==============================================================================================
// PACKAGE: ast (Abstract Syntax Tree)
// PURPOSE: Defines the hierarchical data structures that represent the source code.
//          The AST is generated by the Parser and consumed by the Evaluator.
//          It provides a structured, type-safe representation of the Eloquence language,
//          abstracting away the linear complexity of raw tokens.
// ==============================================================================================

package ast

import (
	"bytes"

	"eloquence/token"
)

// ----------------------------------------------------------------------------------------------
// INTERFACES
// ----------------------------------------------------------------------------------------------

// Node is the base interface for all elements in the Abstract Syntax Tree.
type Node interface {
	TokenLiteral() string
	String() string
}

// Statement represents a node that performs an action but does not return a value.
type Statement interface {
	Node
	statementNode() // Marker method
}

// Expression represents a node that evaluates to a value.
type Expression interface {
	Node
	expressionNode() // Marker method
}

// ----------------------------------------------------------------------------------------------
// ROOT NODE
// ----------------------------------------------------------------------------------------------

// Program is the root node of every AST.
type Program struct {
	Statements []Statement
}

func (p *Program) TokenLiteral() string {
	if len(p.Statements) > 0 {
		return p.Statements[0].TokenLiteral()
	}
	return ""
}

func (p *Program) String() string {
	var out bytes.Buffer
	for _, s := range p.Statements {
		out.WriteString(s.String())
	}
	return out.String()
}

// ----------------------------------------------------------------------------------------------
// STATEMENTS
// ----------------------------------------------------------------------------------------------

// AssignmentStatement represents binding a value to a variable.
// Syntax: x is 5
type AssignmentStatement struct {
	Token token.Token // The 'IDENT' token
	Name  *Identifier
	Value Expression
}

func (as *AssignmentStatement) statementNode()       {}
func (as *AssignmentStatement) TokenLiteral() string { return as.Token.Literal }
func (as *AssignmentStatement) String() string {
	return as.Name.String() + " is " + as.Value.String()
}

// ReturnStatement represents exiting a function with a value.
// Syntax: return 10
type ReturnStatement struct {
	Token       token.Token
	ReturnValue Expression
}

func (rs *ReturnStatement) statementNode()       {}
func (rs *ReturnStatement) TokenLiteral() string { return rs.Token.Literal }
func (rs *ReturnStatement) String() string {
	var out bytes.Buffer
	out.WriteString("return ")
	if rs.ReturnValue != nil {
		out.WriteString(rs.ReturnValue.String())
	}
	return out.String()
}

// ExpressionStatement allows an expression to stand alone as a statement.
// Example: calls like show(x), or simple arithmetic on a line.
type ExpressionStatement struct {
	Token      token.Token // The first token of the expression
	Expression Expression
}

func (es *ExpressionStatement) statementNode()       {}
func (es *ExpressionStatement) TokenLiteral() string { return es.Token.Literal }
func (es *ExpressionStatement) String() string {
	if es.Expression != nil {
		return es.Expression.String()
	}
	return ""
}

// BlockStatement represents a grouped sequence of statements (used in loops/if).
type BlockStatement struct {
	Token      token.Token // The '{' token
	Statements []Statement
}

func (bs *BlockStatement) statementNode()       {}
func (bs *BlockStatement) TokenLiteral() string { return bs.Token.Literal }
func (bs *BlockStatement) String() string {
	var out bytes.Buffer
	for _, s := range bs.Statements {
		out.WriteString(s.String())
	}
	return out.String()
}

// PointerAssignmentStatement represents writing to a memory address.
// Syntax: pointing from ptr is 5
type PointerAssignmentStatement struct {
	Token token.Token // The 'pointing from' token
	Name  *Identifier
	Value Expression
}

func (pas *PointerAssignmentStatement) statementNode()       {}
func (pas *PointerAssignmentStatement) TokenLiteral() string { return pas.Token.Literal }
func (pas *PointerAssignmentStatement) String() string {
	return "pointing from " + pas.Name.String() + " is " + pas.Value.String()
}

// StructDefinitionStatement defines a new custom data type.
// Syntax: define User as struct { name, age }
type StructDefinitionStatement struct {
	Token      token.Token
	Name       *Identifier
	Attributes []*Identifier
}

func (sds *StructDefinitionStatement) statementNode()       {}
func (sds *StructDefinitionStatement) TokenLiteral() string { return sds.Token.Literal }
func (sds *StructDefinitionStatement) String() string {
	var out bytes.Buffer
	out.WriteString("define " + sds.Name.String() + " as struct { ")
	for i, a := range sds.Attributes {
		out.WriteString(a.String())
		if i < len(sds.Attributes)-1 {
			out.WriteString(", ")
		}
	}
	out.WriteString(" }")
	return out.String()
}

// LoopStatement represents a conditional loop (while).
type LoopStatement struct {
	Token     token.Token // The 'while' token
	Condition Expression
	Body      *BlockStatement
}

func (ls *LoopStatement) statementNode()       {}
func (ls *LoopStatement) TokenLiteral() string { return ls.Token.Literal }
func (ls *LoopStatement) String() string {
	return ls.Token.Literal + " " + ls.Condition.String() + " " + ls.Body.String()
}

// RangeLoopStatement represents iterating over a collection.
// Syntax: for item in list { ... }
type RangeLoopStatement struct {
	Token    token.Token // The 'for' token
	Iterator *Identifier
	Iterable Expression
	Body     *BlockStatement
}

func (rl *RangeLoopStatement) statementNode()       {}
func (rl *RangeLoopStatement) TokenLiteral() string { return rl.Token.Literal }
func (rl *RangeLoopStatement) String() string {
	return "for " + rl.Iterator.String() + " in " + rl.Iterable.String() + " " + rl.Body.String()
}

// TryCatchStatement represents error handling blocks.
type TryCatchStatement struct {
	Token        token.Token // The 'try' token
	TryBlock     *BlockStatement
	CatchBlock   *BlockStatement
	FinallyBlock *BlockStatement
}

func (tc *TryCatchStatement) statementNode()       {}
func (tc *TryCatchStatement) TokenLiteral() string { return tc.Token.Literal }
func (tc *TryCatchStatement) String() string {
	var out bytes.Buffer
	out.WriteString("try " + tc.TryBlock.String())
	if tc.CatchBlock != nil {
		out.WriteString(" catch " + tc.CatchBlock.String())
	}
	if tc.FinallyBlock != nil {
		out.WriteString(" finally " + tc.FinallyBlock.String())
	}
	return out.String()
}

// IncludeStatement represents importing another file.
type IncludeStatement struct {
	Token token.Token // The 'include' token
	Path  Expression
}

func (is *IncludeStatement) statementNode()       {}
func (is *IncludeStatement) TokenLiteral() string { return is.Token.Literal }
func (is *IncludeStatement) String() string {
	return "include " + is.Path.String()
}

// ----------------------------------------------------------------------------------------------
// EXPRESSIONS
// ----------------------------------------------------------------------------------------------

type Identifier struct {
	Token token.Token
	Value string
}

func (i *Identifier) expressionNode()      {}
func (i *Identifier) TokenLiteral() string { return i.Token.Literal }
func (i *Identifier) String() string       { return i.Value }

type IntegerLiteral struct {
	Token token.Token
	Value int64
}

func (il *IntegerLiteral) expressionNode()      {}
func (il *IntegerLiteral) TokenLiteral() string { return il.Token.Literal }
func (il *IntegerLiteral) String() string       { return il.Token.Literal }

type FloatLiteral struct {
	Token token.Token
	Value float64
}

func (fl *FloatLiteral) expressionNode()      {}
func (fl *FloatLiteral) TokenLiteral() string { return fl.Token.Literal }
func (fl *FloatLiteral) String() string       { return fl.Token.Literal }

type StringLiteral struct {
	Token token.Token
	Value string
}

func (sl *StringLiteral) expressionNode()      {}
func (sl *StringLiteral) TokenLiteral() string { return sl.Token.Literal }
func (sl *StringLiteral) String() string       { return `"` + sl.Value + `"` }

type CharLiteral struct {
	Token token.Token
	Value rune
}

func (cl *CharLiteral) expressionNode()      {}
func (cl *CharLiteral) TokenLiteral() string { return cl.Token.Literal }
func (cl *CharLiteral) String() string       { return "'" + string(cl.Value) + "'" }

type BooleanLiteral struct {
	Token token.Token
	Value bool
}

func (bl *BooleanLiteral) expressionNode()      {}
func (bl *BooleanLiteral) TokenLiteral() string { return bl.Token.Literal }
func (bl *BooleanLiteral) String() string       { return bl.Token.Literal }

type NilLiteral struct {
	Token token.Token
}

func (nl *NilLiteral) expressionNode()      {}
func (nl *NilLiteral) TokenLiteral() string { return nl.Token.Literal }
func (nl *NilLiteral) String() string       { return "none" }

type PrefixExpression struct {
	Token    token.Token
	Operator string
	Right    Expression
}

func (pe *PrefixExpression) expressionNode()      {}
func (pe *PrefixExpression) TokenLiteral() string { return pe.Token.Literal }
func (pe *PrefixExpression) String() string {
	return "(" + pe.Operator + " " + pe.Right.String() + ")"
}

type InfixExpression struct {
	Token    token.Token
	Left     Expression
	Operator string
	Right    Expression
}

func (ie *InfixExpression) expressionNode()      {}
func (ie *InfixExpression) TokenLiteral() string { return ie.Token.Literal }
func (ie *InfixExpression) String() string {
	return "(" + ie.Left.String() + " " + ie.Operator + " " + ie.Right.String() + ")"
}

type PointerReferenceExpression struct {
	Token token.Token
	Value Expression
}

func (pr *PointerReferenceExpression) expressionNode()      {}
func (pr *PointerReferenceExpression) TokenLiteral() string { return pr.Token.Literal }
func (pr *PointerReferenceExpression) String() string {
	return "(pointing to " + pr.Value.String() + ")"
}

type PointerDereferenceExpression struct {
	Token token.Token
	Value Expression
}

func (pd *PointerDereferenceExpression) expressionNode()      {}
func (pd *PointerDereferenceExpression) TokenLiteral() string { return pd.Token.Literal }
func (pd *PointerDereferenceExpression) String() string {
	return "(pointing from " + pd.Value.String() + ")"
}

type IfExpression struct {
	Token       token.Token
	Condition   Expression
	Consequence *BlockStatement
	Alternative *BlockStatement
}

func (ie *IfExpression) expressionNode()      {}
func (ie *IfExpression) TokenLiteral() string { return ie.Token.Literal }
func (ie *IfExpression) String() string {
	var out bytes.Buffer
	out.WriteString("if " + ie.Condition.String() + " " + ie.Consequence.String())
	if ie.Alternative != nil {
		out.WriteString(" else " + ie.Alternative.String())
	}
	return out.String()
}

type FunctionLiteral struct {
	Token      token.Token
	Parameters []*Identifier
	Body       *BlockStatement
}

func (fl *FunctionLiteral) expressionNode()      {}
func (fl *FunctionLiteral) TokenLiteral() string { return fl.Token.Literal }
func (fl *FunctionLiteral) String() string {
	var out bytes.Buffer
	out.WriteString("takes (")
	for i, p := range fl.Parameters {
		out.WriteString(p.String())
		if i < len(fl.Parameters)-1 {
			out.WriteString(", ")
		}
	}
	out.WriteString(") " + fl.Body.String())
	return out.String()
}

type CallExpression struct {
	Token     token.Token
	Function  Expression
	Arguments []Expression
}

func (ce *CallExpression) expressionNode()      {}
func (ce *CallExpression) TokenLiteral() string { return ce.Token.Literal }
func (ce *CallExpression) String() string {
	var out bytes.Buffer
	out.WriteString(ce.Function.String() + "(")
	for i, a := range ce.Arguments {
		out.WriteString(a.String())
		if i < len(ce.Arguments)-1 {
			out.WriteString(", ")
		}
	}
	out.WriteString(")")
	return out.String()
}

type ArrayLiteral struct {
	Token    token.Token
	Elements []Expression
}

func (al *ArrayLiteral) expressionNode()      {}
func (al *ArrayLiteral) TokenLiteral() string { return al.Token.Literal }
func (al *ArrayLiteral) String() string {
	var out bytes.Buffer
	out.WriteString("[")
	for i, el := range al.Elements {
		out.WriteString(el.String())
		if i < len(al.Elements)-1 {
			out.WriteString(", ")
		}
	}
	out.WriteString("]")
	return out.String()
}

type IndexExpression struct {
	Token token.Token
	Left  Expression
	Index Expression
}

func (ie *IndexExpression) expressionNode()      {}
func (ie *IndexExpression) TokenLiteral() string { return ie.Token.Literal }
func (ie *IndexExpression) String() string {
	return "(" + ie.Left.String() + "[" + ie.Index.String() + "])"
}

type MapLiteral struct {
	Token token.Token
	Pairs map[Expression]Expression
}

func (ml *MapLiteral) expressionNode()      {}
func (ml *MapLiteral) TokenLiteral() string { return ml.Token.Literal }
func (ml *MapLiteral) String() string {
	return "{...}"
}

type StructField struct {
	Name  *Identifier
	Value Expression
}

type StructInstantiationExpression struct {
	Token  token.Token
	Name   *Identifier
	Fields []StructField
}

func (sie *StructInstantiationExpression) expressionNode()      {}
func (sie *StructInstantiationExpression) TokenLiteral() string { return sie.Token.Literal }
func (sie *StructInstantiationExpression) String() string {
	var out bytes.Buffer
	out.WriteString(sie.Name.String() + " { ")
	for i, f := range sie.Fields {
		out.WriteString(f.Name.String() + ": " + f.Value.String())
		if i < len(sie.Fields)-1 {
			out.WriteString(", ")
		}
	}
	out.WriteString(" }")
	return out.String()
}

type FieldAccessExpression struct {
	Token  token.Token
	Object Expression
	Field  *Identifier
}

func (fae *FieldAccessExpression) expressionNode()      {}
func (fae *FieldAccessExpression) TokenLiteral() string { return fae.Token.Literal }
func (fae *FieldAccessExpression) String() string {
	return "(" + fae.Object.String() + "." + fae.Field.String() + ")"
}
